### ISSUE TITLE
Add leading and ending space

### ISSUE THREAD

**Issue by djcliffdeguzman** [nockscitney/SeratoNowPlaying#8]
Please add by default a leading and ending space to the string that gets written in the specified .txt file.

**Comment by nockscitney** [comment]
Thanks for raising the issue Cliff. As soon as I’m back with my computer, I’ll get to work on this for you

**Comment by nockscitney** [comment]
The issue is now resolved. Leading and trailing spaces have been added to track label write method - The latest releases are:

Serato Now Playing: https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snp-1.1.1.0
Serato Now Playing Lite: https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snpl-1.0.1.0
